language: node_js
node_js: 
  - '9.11.1'


branches:
  only:
    - master


cache:
  directories:
    - node_modules


install: 
  - yarn install


before_script:


script: 
 - yarn run build


deploy:
  provider: pages
  skip_cleanup: true
  keep-history: true
  github_token: ${GH_TOKEN}
  target-branch: gh-pages
  on: 
    branch: master


after_deploy:
  - echo "deploy successful"


after_script:
  - cd dist
  - git init 
  - git config user.name "${U_NAME}"
  - git config user.email "${U_EMAIL}"
  - git add .
  - git commit -m "by travis boot"
  # - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:${P_BRANCH}
  - git push --force "https://${GH_TOKEN}@${GH_REF}" master:gh-pages
  

env:
 global:
   - GH_REF: github.com/Ele-fed/test-travis-vue.git
   #- P_BRANCH: gh-pages
