language: node_js
node_js: 
  - '9.11.1'

install: 
  - yarn install

before_script:

script: 
  - yarn run build


before_deploy:
  - cd ./dist
  - git init 
  - git config user.name "${U_NAME}"
  - git config user.email "${U_EMAIL}"
  - git add .
  - git commit -m "run build from boot"
  - git puhs --force --quiet "https://${GH_TOKEN}@${GH_REF}" origin:{P_BRANCH}


deploy:
  provider: pages
  skip_cleanup: true
  keep-history: true
  github_token: ${GH_TOKEN}
  on: 
    branch: master


after_deploy:


after_script:


