language: node_js
node_js: 
  - '9.11.1'

install: 
  - yarn install

before_script:

script: 
  - yarn run build

before_deploy:

deploy:
  provider: pages
  skip_cleanup: true
  keep-history: true
  github_token: ${GH_TOKEN}
  target-branch: gh-pages
  on: 
    branch: master


after_deploy:

after_script:
  - cd ./dist
  - git init 
  - git config user.name "${U_NAME}"
  - git config user.email "${U_EMAIL}"
  - git add .
  - git commit -m "run build from boot"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:${P_BRANCH}

env:
 global:
   #- GH_REF: github.com/yimogit/metools.git
   #- P_BRANCH: gh-pages
